# Generated by Django 4.2.3 on 2023-07-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_appointment_choosen_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
